apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - git::https://github.com/majordookie/argocd-example-apps.git//kustomize-guestbook?ref=master

patchesStrategicMerge:
  - version.yaml